services:
  - type: web
    name: ğš‡ğ™´ğ™½ğ™°-ğ™¼ğ™³
    env: docker
    region: Frankfurt
    plan: free
    envVars:
      - key: SESSION_ID
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: SUDO
        sync: false
